hotspots:
  - x: 452.126
    y: 574.864
    r: 1.310
    n_pop: 3000
    id: "h1"

  - x: 454.975
    y: 573.61
    r: 1.420
    n_pop: 2000
    id: "h2"
  
  - x: 452.630
    y: 573.439
    r: 0.737
    n_pop: 1500
    id: "h3"

workspots:
  - x: 456.49
    y: 573.588
    r: 1.106
    id: "w1"
    

  - x: 452.232
    y: 572.986
    r: 0.550
    id: "w2"

  - x: 451.691
    y: 573.623
    r: 0.6
    id: "w3"

peakhours:
  am:
  - hour: 9

  pm:
  - hour: 16
  - hour: 18


