hotspots:
  - x: 452.257
    y: 574.384
    r: 1.280
    n_pop: 
    id: "h1"

  - x: 454.667
    y: 574.131
    r: 0.74
    n_pop: 
    id: "h2"
  
  - x: 457.467
    y: 573.989
    r: 0.55
    n_pop: 
    id: "h3"

  - x: 457.127
    y: 573.658
    r: 0.78
    n_pop: 
    id: "h4"
  - x: 456.124
    y: 573.851
    r: 0.47
    n_pop: 
    id: "h5"
  - x: 455.083
    y: 573.766
    r: 0.530
    n_pop: 
    id: "h6"
  - x:
    y:
    r:
    n_pop: 
    id: "h7"


workspots:
  - x: 456.49
    y: 573.588
    r: 1.106
    id: "w1"
    

  - x: 452.232
    y: 572.986
    r: 0.550
    id: "w2"

  - x: 451.691
    y: 573.623
    r: 0.6
    id: "w3"

peakhours:
  am:
  - hour: 9

  pm:
  - hour: 16
  - hour: 18


